// ── Hardcoded whisky list (1–100) ─────────────────────────────────────────────
const WHISKY_LIST = [
  'Laphroaig 10 Year',
  'Lagavulin 16 Year',
  'Ardbeg Ten',
  'Talisker 10 Year',
  'Oban 14 Year',
  'Macallan 12 Year Sherry Oak',
  'Glenfiddich 12 Year',
  'The Balvenie DoubleWood 12',
  'Glenmorangie The Original',
  'Highland Park 12 Year (Viking Honour)',
  'Bruichladdich The Classic Laddie',
  'Aberlour 12 Year Double Cask',
  'Bunnahabhain 12 Year',
  'Caol Ila 12 Year',
  'Springbank 10 Year',
  'Glenlivet 12 Year',
  'Dalwhinnie 15 Year',
  'Bowmore 12 Year',
  'Jura 10 Year',
  'Mortlach 12 Year (The Wee Witchie)',
  'Glendronach 12 Year',
  'Old Pulteney 12 Year',
  'Glenfarclas 105',
  'Kilchoman Machir Bay',
  'Port Charlotte 10 Year',
  'Glenkinchie 12 Year',
  'Clynelish 14 Year',
  'Craigellachie 13 Year',
  'Benromach 10 Year',
  'Arran 10 Year',
  'Deanston 12 Year',
  'Royal Brackla 12 Year',
  'Tamdhu 12 Year',
  'Glengoyne 10 Year',
  'Johnnie Walker Black Label',
  'Johnnie Walker Blue Label',
  'Chivas Regal 12 Year',
  'Monkey Shoulder (Blended Malt)',
  'Compass Box The Peat Monster',
  "Dewar's White Label",
  'Buffalo Trace',
  'Eagle Rare 10 Year',
  "Blanton's Single Barrel",
  "Maker's Mark",
  'Woodford Reserve',
  'Bulleit Bourbon',
  'Knob Creek 9 Year',
  'Wild Turkey 101',
  "Basil Hayden's",
  'Old Forester 1910',
  'Elijah Craig Small Batch',
  'Four Roses Single Barrel',
  "Michter's US*1 Bourbon",
  "Angel's Envy (Port Wine Finish)",
  'Booker\'s (Small Batch)',
  'George T. Stagg',
  'Pappy Van Winkle 15 Year',
  "Jack Daniel's Old No. 7",
  "Jack Daniel's Single Barrel Select",
  'George Dickel No. 12',
  'Rittenhouse Rye',
  'Sazerac Rye',
  'WhistlePig 10 Year Rye',
  'High West Rendezvous Rye',
  'Knob Creek Rye',
  'Bulleit Rye',
  'Old Overholt Rye',
  'Balcones Texas Single Malt',
  'Westward American Single Malt',
  "Stranahan's Colorado Whiskey",
  'Jameson Original',
  'Bushmills Original',
  'Redbreast 12 Year',
  'Teeling Small Batch',
  'Tullamore D.E.W.',
  'Green Spot',
  'Yellow Spot',
  'Powers Gold Label',
  "Writer's Tears Copper Pot",
  'Connemara Peated Single Malt',
  'Roe & Co',
  'Slane Irish Whiskey',
  'Knappogue Castle 12 Year',
  'Redbreast Lustau Edition',
  'Midleton Very Rare',
  'Yamazaki 12 Year (Japan)',
  'Hibiki Japanese Harmony (Japan)',
  'Nikka From The Barrel (Japan)',
  'Hakushu 12 Year (Japan)',
  'Suntory Toki (Japan)',
  'Yoichi Single Malt (Japan)',
  'Akashi White Oak (Japan)',
  'Kavalan Classic (Taiwan)',
  'Amrut Fusion (India)',
  'Paul John Edited (India)',
  'Crown Royal Deluxe (Canada)',
  'Lot No. 40 Rye (Canada)',
  'Penderyn Madeira Finish (Wales)',
  'Starward Nova (Australia)',
  'Mackmyra Svensk Ek (Sweden)'
];

// ── Whisky info (region, description, avg UK/GBP price) ──────────────────────
const WHISKY_DATA = {
  1:  { region: 'Islay, Scotland',           price: '£38',  desc: 'Intensely peated with medicinal iodine, seaweed, and bonfire smoke followed by a sweet vanilla finish.' },
  2:  { region: 'Islay, Scotland',           price: '£68',  desc: 'Rich and elegant peat smoke with dark dried fruit, sea salt, and a long warming finish.' },
  3:  { region: 'Islay, Scotland',           price: '£48',  desc: 'Punchy peat and tarry rope aromas give way to chocolate, citrus zest, and a famously long dry finish.' },
  4:  { region: 'Isle of Skye, Scotland',    price: '£43',  desc: 'Maritime and peaty with waves of black pepper, briny sea spray, and a warming spiced finish.' },
  5:  { region: 'Western Highlands, Scotland', price: '£58', desc: 'Gently peated coastal dram with sea salt, honey, dried fruit, and a clean malty sweetness.' },
  6:  { region: 'Speyside, Scotland',        price: '£62',  desc: 'Sherry-cask matured with rich notes of dark dried fruit, chocolate orange, ginger, and warming oak spice.' },
  7:  { region: 'Speyside, Scotland',        price: '£32',  desc: 'Light and approachable with fresh pear, vanilla cream, and a delicate hint of oak. The world\'s best-selling single malt.' },
  8:  { region: 'Speyside, Scotland',        price: '£48',  desc: 'Honey, vanilla, and fresh fruit from the bourbon cask combine with sherry-inspired dried fruit and baking spice.' },
  9:  { region: 'Highlands, Scotland',       price: '£38',  desc: 'Tallest stills in Scotland produce a light, floral, and elegant dram with peach, vanilla, and citrus blossom.' },
  10: { region: 'Orkney, Scotland',          price: '£42',  desc: 'Subtle heather-peat smoke, heather honey, dried orange peel, and a hint of maritime brine.' },
  11: { region: 'Islay, Scotland',           price: '£42',  desc: 'Unpeated Islay malt with floral barley, fresh citrus, and a gentle coastal brininess.' },
  12: { region: 'Speyside, Scotland',        price: '£42',  desc: 'Matured in both American and European oak casks delivering toffee, rich fruit, and warming spice.' },
  13: { region: 'Islay, Scotland',           price: '£42',  desc: 'Rare unpeated Islay whisky with rich dried fruit, hazelnut, sea salt, and a smooth, mellow finish.' },
  14: { region: 'Islay, Scotland',           price: '£43',  desc: 'Lighter Islay peat style with floral notes, fresh lemon zest, and a gentle smoky sweetness.' },
  15: { region: 'Campbeltown, Scotland',     price: '£52',  desc: 'Waxy and briny with dried apricot, light peat, and the distinctive Campbeltown oiliness.' },
  16: { region: 'Speyside, Scotland',        price: '£32',  desc: 'Light, floral, and fruity — the approachable introduction to Speyside malts with pear and floral notes.' },
  17: { region: 'Highlands, Scotland',       price: '£42',  desc: 'High-altitude distillery producing soft heather honey, light vanilla, and delicate floral notes.' },
  18: { region: 'Islay, Scotland',           price: '£37',  desc: 'Gentlest of the Islay malts with tropical fruit, toffee sweetness, and a soft peat smoke undercurrent.' },
  19: { region: 'Isle of Jura, Scotland',    price: '£32',  desc: 'Light, accessible malt with orchard fruit, soft vanilla, and just a whisper of island peat.' },
  20: { region: 'Speyside, Scotland',        price: '£48',  desc: 'Rich and meaty from the unique 2.81-times distillation process — dried fruit, nutmeg, and robust oak.' },
  21: { region: 'Highlands, Scotland',       price: '£48',  desc: 'PX and Oloroso sherry casks deliver waves of dark chocolate, raisins, walnut, and Christmas cake spice.' },
  22: { region: 'Highlands, Scotland',       price: '£38',  desc: 'Coastal maritime character with toffee, honey, and a distinctive herbal saltiness from the North Sea.' },
  23: { region: 'Speyside, Scotland',        price: '£57',  desc: 'Cask-strength sherry bomb at 60% ABV — intense raisins, dark fruit, sultanas, and powerful warming spice.' },
  24: { region: 'Islay, Scotland',           price: '£48',  desc: 'Youthful Islay peat with bright citrus, fresh vanilla, and an approachable gentle smoke from Atlantic-dried barley.' },
  25: { region: 'Islay, Scotland',           price: '£52',  desc: 'Heavily peated yet complex with lemon curd, vanilla, and layers of gentle smoke building to a long sweet finish.' },
  26: { region: 'Lowlands, Scotland',        price: '£42',  desc: 'Light and delicate Lowlands expression — fresh cut grass, floral blossom, and a clean soft finish.' },
  27: { region: 'Highlands, Scotland',       price: '£47',  desc: 'Distinctive waxy and coastal character with dried fruit, pepper, and a long lingering spicy finish.' },
  28: { region: 'Speyside, Scotland',        price: '£47',  desc: 'Unusual and characterful with tropical fruit, a meaty sulfurous note, and banana custard sweetness.' },
  29: { region: 'Speyside, Scotland',        price: '£37',  desc: 'Lightly peated Speyside with fresh vanilla, raspberry jam, and a hint of smoke — great value.' },
  30: { region: 'Isle of Arran, Scotland',   price: '£37',  desc: 'Fruity and coastal with fresh apple, vanilla cream, and a gentle island brine on the finish.' },
  31: { region: 'Highlands, Scotland',       price: '£37',  desc: 'Unpeated Highland malt with rich malt, creamy vanilla, and a honeyed sweetness — approachable and clean.' },
  32: { region: 'Highlands, Scotland',       price: '£42',  desc: 'Royal-warranted distillery producing dried fruit, caramel, gentle spice, and a silky smooth texture.' },
  33: { region: 'Speyside, Scotland',        price: '£42',  desc: 'Exclusively Oloroso sherry-matured producing rich Christmas cake, dark plum, and warming winter spices.' },
  34: { region: 'Highlands/Lowlands border, Scotland', price: '£37', desc: 'Completely unpeated with toffee apple, malt biscuit, and a honeyed sweetness — relaxed and charming.' },
  35: { region: 'Blended Scotch',            price: '£32',  desc: 'The iconic blended Scotch with a smoky backbone, ripe fruit, and vanilla — the global benchmark.' },
  36: { region: 'Blended Scotch',            price: '£195', desc: 'Ultra-premium blend using rare aged whiskies — silky smooth texture, extraordinary complexity, and a velvet finish.' },
  37: { region: 'Blended Scotch',            price: '£27',  desc: 'Smooth, honeyed, and approachable blended Scotch with apple, hazelnut, and a gentle hint of spice.' },
  38: { region: 'Blended Malt Scotch',       price: '£27',  desc: 'Three Speyside single malts blended for an easy-drinking, vanilla-rich, and gently spiced dram.' },
  39: { region: 'Blended Malt Scotch',       price: '£47',  desc: 'A peated blended malt from the innovative Compass Box — camp fire smoke, vanilla, and bright fruit.' },
  40: { region: 'Blended Scotch',            price: '£20',  desc: 'Light, sweet, and very accessible blended Scotch — soft vanilla and fresh cereal, great as a mixer.' },
  41: { region: 'Kentucky, USA',             price: '£28',  desc: 'The flagship of the Buffalo Trace distillery — caramel, vanilla, and gentle fruit with a clean spiced finish.' },
  42: { region: 'Kentucky, USA',             price: '£38',  desc: 'Single-barrel bourbon aged 10 years — rich toffee, dark orange peel, leather, and a long elegant finish.' },
  43: { region: 'Kentucky, USA',             price: '£65',  desc: 'Cult single-barrel bourbon with floral honey, citrus, and a complex structure — famously sealed with a horse stopper.' },
  44: { region: 'Kentucky, USA',             price: '£32',  desc: 'Soft and sweet red-winter-wheat bourbon with caramel, vanilla, and a gentle spice. The "handmade" bourbon.' },
  45: { region: 'Kentucky, USA',             price: '£37',  desc: 'Well-balanced and approachable — rich dried fruit, chocolate, caramel, and warming spice from a triple maturation.' },
  46: { region: 'Kentucky, USA',             price: '£27',  desc: 'High-rye mash bill giving bold spice, cherry, and vanilla notes — reliable and great value.' },
  47: { region: 'Kentucky, USA',             price: '£37',  desc: 'Full-flavoured and richly oaked after 9 years — deep caramel, vanilla, toasted oak, and a lingering warmth.' },
  48: { region: 'Kentucky, USA',             price: '£27',  desc: 'Bold and high-proof at 101, with powerful vanilla, caramel, and a satisfying old-fashioned spice. Legendary value.' },
  49: { region: 'Kentucky, USA',             price: '£47',  desc: 'Light and approachable high-rye bourbon with peppery spice, citrus, and a fresh, easy-drinking character.' },
  50: { region: 'Kentucky, USA',             price: '£47',  desc: 'Finished in a second new charred oak barrel adding deep baking spice, dark caramel, and a rich velvety texture.' },
  51: { region: 'Kentucky, USA',             price: '£37',  desc: 'Classic small-batch bourbon with caramel, vanilla, and dark fruit — approachable depth and excellent value.' },
  52: { region: 'Kentucky, USA',             price: '£47',  desc: 'Floral and fruity single barrel from one of ten unique proprietary yeast strains — complex and rewarding.' },
  53: { region: 'Kentucky, USA',             price: '£47',  desc: 'Premium small-batch bourbon with caramel, vanilla, dried fruit, and a polished finish from careful barrel selection.' },
  54: { region: 'Kentucky, USA',             price: '£52',  desc: 'Finished in ruby port wine casks — sweet dark fruit, vanilla, and a distinctly smooth, wine-kissed sweetness.' },
  55: { region: 'Kentucky, USA',             price: '£70',  desc: 'Uncut and unfiltered cask-strength small-batch bourbon — bold caramel, vanilla, baking spice, and raw oak power.' },
  56: { region: 'Kentucky, USA',             price: '£250', desc: 'Buffalo Trace Antique Collection legend — massive complexity, intense fruit, oak, and spice at high proof. Near impossible to find.' },
  57: { region: 'Kentucky, USA',             price: '£600', desc: 'The world\'s most coveted bourbon — caramel, vanilla, and extraordinary depth from 15 years in exceptional barrels.' },
  58: { region: 'Tennessee, USA',            price: '£24',  desc: 'Charcoal-mellowed Tennessee whiskey — smooth banana, vanilla, and caramel with that distinctive Lincoln County character.' },
  59: { region: 'Tennessee, USA',            price: '£47',  desc: 'Premium single-barrel Tennessee whiskey — deeper oak, vanilla spice, and toasted caramel with a long warming finish.' },
  60: { region: 'Tennessee, USA',            price: '£27',  desc: 'Smooth and corn-forward charcoal-filtered Tennessee whiskey — lighter style with gentle caramel and easy sweetness.' },
  61: { region: 'Pennsylvania, USA',         price: '£27',  desc: 'Bottled-in-bond straight rye at 100 proof — bold spice, rye grain, and herbal notes. A cocktail bar essential.' },
  62: { region: 'Kentucky, USA',             price: '£37',  desc: 'Buffalo Trace\'s rye expression — black pepper, anise, orange peel, and a dry, pleasingly bitter finish.' },
  63: { region: 'Vermont, USA',              price: '£68',  desc: 'Bold and complex Canadian-sourced rye aged in Vermont — rich caramel, warming spice, and a long elegant finish.' },
  64: { region: 'Utah, USA',                 price: '£52',  desc: 'A blend of two straight ryes creating layers of caramel, spice, dried fruit, and a pleasingly complex depth.' },
  65: { region: 'Kentucky, USA',             price: '£37',  desc: 'Full-bodied and bold rye from Knob Creek — vanilla, spice, and robust oak from long aging in charred barrels.' },
  66: { region: 'Indiana, USA',              price: '£27',  desc: 'High rye content in an accessible, smooth style — light spice, vanilla, and an easy-drinking character.' },
  67: { region: 'Pennsylvania, USA',         price: '£22',  desc: 'America\'s original rye whiskey — straightforward, affordable, with light spice and a clean accessible finish.' },
  68: { region: 'Texas, USA',               price: '£60',  desc: 'Robust Texas-made American single malt — bold dried fruit, oak, and a distinctive richness from the extreme Texas climate.' },
  69: { region: 'Oregon, USA',              price: '£60',  desc: 'Pacific Northwest craft single malt influenced by local beer culture — fruity, rich, and innovatively American.' },
  70: { region: 'Colorado, USA',            price: '£55',  desc: 'Colorado-made American single malt with fresh vanilla, honeyed malt, and a gentle oak warmth.' },
  71: { region: 'Ireland',                  price: '£23',  desc: 'Triple-distilled and blended — light, smooth, and approachable with vanilla, floral notes, and a clean easy finish.' },
  72: { region: 'Ireland',                  price: '£21',  desc: 'The world\'s oldest licensed distillery — triple-distilled with honey, light malt, and a smooth accessible character.' },
  73: { region: 'Ireland',                  price: '£47',  desc: 'Pure pot still Irish whiskey matured in sherry casks — rich dried fruit, spice, and a signature creamy pot-still texture.' },
  74: { region: 'Ireland',                  price: '£37',  desc: 'Small-batch Irish whiskey finished in rum casks — tropical fruit, vanilla, and a pleasingly innovative sweetness.' },
  75: { region: 'Ireland',                  price: '£23',  desc: 'Blended Irish whiskey with light fruit, vanilla, and a gentle herbal note — the friendly Irish crowd-pleaser.' },
  76: { region: 'Ireland',                  price: '£42',  desc: 'Single pot still Irish whiskey with orchard fruit, spice, fresh barley, and a delightfully creamy mouthfeel.' },
  77: { region: 'Ireland',                  price: '£62',  desc: '12-year single pot still finished in Malaga wine casks — exotic fruit, creamy pot-still spice, and remarkable depth.' },
  78: { region: 'Ireland',                  price: '£23',  desc: 'Traditional Irish pot still whiskey — full-bodied with spicy pot-still character, grain, and a warming dry finish.' },
  79: { region: 'Ireland',                  price: '£37',  desc: 'A blend of single malt and pot still — honey, vanilla, floral notes, and a soft approachable Irish character.' },
  80: { region: 'Ireland',                  price: '£37',  desc: 'Rare peated Irish whiskey from Connemara — light heather smoke over sweet malt and a gentle coastal saltiness.' },
  81: { region: 'Ireland',                  price: '£30',  desc: 'Modern Dublin blended whiskey with smooth fruit, light vanilla, and an easy-going accessible character.' },
  82: { region: 'Ireland',                  price: '£27',  desc: 'Triple-cask matured Irish blend — smooth toffee, fruit, and a light spice from virgin Irish oak.' },
  83: { region: 'Ireland',                  price: '£42',  desc: 'Single malt aged in sherry casks — light, floral, honey, and a delicate refined character from a historic distillery.' },
  84: { region: 'Ireland',                  price: '£57',  desc: 'Redbreast finished in Lustau sherry casks — intense dark fruit, creamy pot-still texture, and exceptional richness.' },
  85: { region: 'Ireland',                  price: '£135', desc: 'Annual vintage release from Midleton — exceptionally complex and rich blended pot still Irish whiskey.' },
  86: { region: 'Speyside, Japan',          price: '£120', desc: 'Fruity and fragrant with plum, raspberry, and exotic spice from rare Japanese Mizunara oak casks.' },
  87: { region: 'Japan',                    price: '£65',  desc: 'Beautifully balanced blend of malt and grain whiskies — floral, honeyed, and delicately complex with subtle smoke.' },
  88: { region: 'Japan',                    price: '£52',  desc: 'Bottled at 51.4% without dilution — rich and complex with dried fruit, rye spice, and a remarkably smooth mouthfeel.' },
  89: { region: 'Highlands, Japan',         price: '£120', desc: 'Made at Japan\'s highest distillery — fresh green apple, mint, and gentle forest peat with a clean crisp finish.' },
  90: { region: 'Japan',                    price: '£37',  desc: 'Suntory\'s approachable blend — light citrus, honey, and soft grain, perfect as a highball.' },
  91: { region: 'Hokkaido, Japan',          price: '£75',  desc: 'Maritime and robust single malt from Hokkaido — bold peated character with dried fruit and a striking sea-salt finish.' },
  92: { region: 'Akashi, Japan',            price: '£32',  desc: 'Accessible entry-level Japanese whisky — light, fruity, and easy-drinking with gentle oak and vanilla.' },
  93: { region: 'Taiwan',                   price: '£60',  desc: 'Tropical climate maturation in ex-bourbon casks — intense tropical fruit, vanilla, and rich caramel in record time.' },
  94: { region: 'Bangalore, India',         price: '£47',  desc: 'Blend of peated Scottish malt and unpeated Indian barley — complex and award-winning with smoke, mango, and spice.' },
  95: { region: 'Goa, India',               price: '£42',  desc: 'Lightly peated Indian single malt — tropical fruit, vanilla, and gentle smoke from rapid tropical maturation.' },
  96: { region: 'Canada',                   price: '£27',  desc: 'The best-selling Canadian whisky — smooth, light, and easy-drinking with vanilla and a gentle grain sweetness.' },
  97: { region: 'Canada',                   price: '£37',  desc: '100% rye grain pot still whisky — bold, spicy, and fruity with a traditional style that punches above its price.' },
  98: { region: 'Wales',                    price: '£42',  desc: 'Matured in Madeira wine casks — light, fruity, and floral with a gentle wine-influenced sweetness. Proudly Welsh.' },
  99: { region: 'Victoria, Australia',      price: '£42',  desc: 'Aged in Australian red wine casks — vibrant fruit, rich malt, and a wine-forward sweetness from the innovative Starward distillery.' },
  100:{ region: 'Sweden',                   price: '£52',  desc: 'Matured in Swedish oak — light, floral, and vanilla-forward with a hint of dill and juniper from the Nordic terroir.' }
};

// ── Storage keys ─────────────────────────────────────────────────────────────
const ENTRIES_KEY  = 'whisky-club-entries';
const USED_KEY     = 'whisky-club-used';
const REVIEWS_KEY  = 'whisky-club-reviews';
const PRICES_KEY   = 'whisky-club-prices';
const SESSION_KEY  = 'whisky-club-session';

// ── JSONBin cloud sync ────────────────────────────────────────────────────────
const JSONBIN_BASE = 'https://api.jsonbin.io/v3';
const JSONBIN_KEY  = '$2a$10$7sndeshKqvuoqFr.LDI8eOHtIomBtO83.wPskt3Y33i0NfNekDisC';
const JSONBIN_BIN  = '69b6b0bbb7ec241ddc6e2ca0';

// ── Club members ──────────────────────────────────────────────────────────────
const PERSONS = ['Kev', 'John', 'Dan', 'Morgan'];

// ── App state ─────────────────────────────────────────────────────────────────
let entries  = JSON.parse(localStorage.getItem(ENTRIES_KEY)  || '{}');
let usedNums = JSON.parse(localStorage.getItem(USED_KEY)     || '[]');
let reviews  = JSON.parse(localStorage.getItem(REVIEWS_KEY)  || '[]');
let prices   = JSON.parse(localStorage.getItem(PRICES_KEY)   || '[]');

let currentNum     = null; // set to the active slot's number when reviewing
let currentNum1    = null; // slot 1 selected number
let currentNum2    = null; // slot 2 selected number
let activeSlot     = null; // which slot's review form is open (1 or 2)
let currentRatings = {};
let rollsLocked    = false; // roll buttons unlocked by default
