// ── Hardcoded whisky list (1–153) ─────────────────────────────────────────────
const WHISKY_LIST = [
  'Aberfeldy 21 Years in Age',
  "Aberlour A'bunadh",
  'Aerstone Sea Cask / Land Cask',
  'Amrut Fusion',
  'anCnoc 18 Years Old',
  'Ardbeg 10 Years Old',
  'The Ardmore Aged 20 Years',
  'Auchentoshan American Oak',
  'Balblair Vintage 2005',
  "Ballantine's Barrel Smooth",
  'The Balvenie PortWood Aged 21 Years',
  "Basil Hayden's",
  'The BenRiach Curiositas, Peated Malt',
  'Benromach Organic',
  'Bernheim Original Aged 7 Years',
  'Bowmore Aged 15 Years',
  'Bruichladdich The Classic Laddie',
  'Buffalo Trace',
  'Bunnahabhain 18 Year Old',
  'Bushmills Aged 16 Years',
  'Caol Ila Aged 12 Years',
  'The Chita',
  'Chivas Regal 25',
  'Clynelish Aged 14 Years',
  'Cotswolds',
  'Crown Royal Deluxe',
  'The Dalmore Port Wood Reserve',
  'Dalwhinnie 15 Years Old',
  'Deanston Aged 12 Years',
  "Dewar's Aged 25 Years, The Signature",
  'Eagle Rare',
  'Elijah Craig Small Batch',
  'The English Original',
  'Glen Breton Rare',
  'Glen Grant Aged 18 Years',
  'Glen Marnoch Speyside',
  'Glen Moray Fired Oak',
  'Glen Scotia Aged 15 Years',
  'Glenfarclas 105',
  'Glenfiddich Winter Storm',
  'Glenglassaugh Revival',
  'Glengoyne 21 Years',
  'The Glenlivet Nadurra',
  'Glenmorangie The Quinta Ruban',
  'Glenrothes 18 Years Old',
  'Gooderham & Worts Four Grain',
  "Great King Street Artist's Blend",
  'Green Spot',
  'Highland Park 18 Year Old Viking Pride',
  'House of Hazelwood Aged 18 Years',
  'Hudson Manhattan Rye',
  "J. P. Wiser's 18 Years Old",
  'Jameson Limited Reserve, 18 Years Old',
  "Jefferson's Very Small Batch",
  'Johnnie Walker Black Label',
  'Jura Aged 18 Years',
  'Kavalan Concertmaster',
  'Kilchoman Sanaig',
  'Kingsbarns Dream to Dram',
  'Knob Creek Kentucky Straight',
  'Label 5 Classic Black',
  'Lagavulin Aged 8 Years',
  'Laphroaig Quarter Cask',
  'Loch Lomond Aged 12 Years',
  'London Rye',
  'Longrow Peated',
  'Lost Spirits Abomination',
  'Lot No. 40',
  'Mackmyra Svensk EK',
  "Maker's Mark",
  'Mars Maltage Cosmo',
  'Mellow Corn',
  'Method and Madness Single Grain',
  "Michter's US+1 Kentucky Straight Bourbon",
  'Millstone 100 Rye',
  'Monkey Shoulder',
  'Mortlach Aged 12 Years',
  'Nikka From the Barrel',
  'Oban 14 Years Old',
  'Old Forester 86 Proof',
  'Old Pulteney Aged 18 Years',
  'Paul John Brilliance',
  'Penderyn Madeira Finish',
  'Pike Creek 10 Year Old',
  'Port Askaig Aged 8 Years',
  'Redbreast Aged 12 Years',
  'Rock Island',
  'Scapa Skiren',
  'Smokehead High Voltage',
  'Springbank Aged 10 Years',
  'Starward',
  'Talisker Aged 10 Years',
  'Tamdhu Batch Strength',
  'Teeling Single Malt',
  'Teerenpeli Aged 10 Years',
  'Tobermory Aged 12 Years',
  'Suntory Toki',
  'Tullamore D.E.W.',
  'Westland American Oak',
  'WhistlePig 10 Year Old',
  "Woodford Reserve Distiller's Select",
  'Arbikie 1794 Highland Rye',
  'Arran 10 Years Old',
  'Balblair 12 Year Old',
  'Ballykeefe Single Estate',
  'Benriach The Twelve',
  'Benromach Aged 15 Years',
  'Bimber Oloroso Cask',
  'Bladnoch Vinaya',
  'Blaze Scotch Whisky',
  'Blue Spot Aged 7 Years',
  'Compass Box Artist Blend',
  'Cutty Sark Aged 12 Years',
  'Deanstone 12 Years Old',
  'The Deveron Aged 12 Years',
  "Dewar's Double Double",
  "Dewar's Japanese Smooth",
  'Ezra Brooks',
  'Fettercairn Aged 12 Years',
  'The Gladstone Axe American Oak',
  'Glen Garioch Aged 12 Years',
  'Glen Scotia Victoriana',
  'The GlenAllachie Aged 12 Years',
  'Glencadam Aged 15 Years',
  'The GlenDronach Revival',
  'Glenfarclas Aged 25 Years',
  'Glenfiddich Solera 15',
  'Glenglassaugh 12 Years Old',
  'Glengoyne Aged 10 Years',
  'Glenkinchie 12 Year Old',
  'Hudson Whiskey NY Bright Lights, Big Bourbon',
  'InchDairnie RyeLaw',
  'J. G. Thomson Blended Malt Range',
  'Jameson 18 Years',
  'Kavalan Distillery Select No1',
  'Kyro Malt Rye',
  'Lindores MCDXCIV',
  'Loch Lomond Peated Single Grain',
  "Macaloney's Caledonian Glenloy",
  "MacNair's Lum Reek",
  'Masthouse Column Malt Whisky',
  'Milk & Honey Classic',
  'New Riff Kentucky Straight Bourbon',
  'Rampur Asava',
  'Starward Nova',
  'Teeling Small Batch',
  'Teerenpeli Kulo',
  'Torabhaig The Legacy Series',
  'Waterford Biodynamic Luna 1.1',
  'West Cork Bog Oak Charred Cask',
  'Wild Turkey 101 Kentucky Straight Bourbon',
  'Wire Works Single Malt English Whisky',
  'Writers Tears Copper Pot'
];

// ── Whisky info (category/type, avg UK price, brief description) ──────────────
const WHISKY_DATA = {
  1:   { region: 'Scotch Single Malt',      price: '~£70',  desc: 'Honey-rich Highland malt aged 21 years in ex-bourbon casks, with vanilla, dried fruit and a gentle oakiness.' },
  2:   { region: 'Scotch Single Malt',      price: '~£55',  desc: 'Non-chill-filtered Speyside bottled at cask strength, packed with rich sherry, dried fruit and spice.' },
  3:   { region: 'Scotch Single Malt',      price: '~£25',  desc: 'Coastal Ayrshire malt available in both sea-cask (light, briny) and land-cask (fruity, smooth) styles.' },
  4:   { region: 'Indian Single Malt',      price: '~£50',  desc: 'Award-winning Indian malt using both peated Scottish and unpeated Indian barley, with tropical fruit and smoke.' },
  5:   { region: 'Scotch Single Malt',      price: '~£55',  desc: 'Fruity and floral Highland malt aged 18 years with notes of vanilla, heather and a hint of smoke.' },
  6:   { region: 'Scotch Single Malt',      price: '~£45',  desc: 'Iconic Islay malt aged 10 years; intensely peaty with brine, tar and a surprisingly sweet finish.' },
  7:   { region: 'Scotch Single Malt',      price: '~£75',  desc: 'Rare 20-year-old expression from the Highland distillery known for smoky, lightly peated character.' },
  8:   { region: 'Scotch Single Malt',      price: '~£30',  desc: 'Light triple-distilled Lowland malt aged in American oak, offering fresh citrus and vanilla notes.' },
  9:   { region: 'Scotch Single Malt',      price: '~£65',  desc: 'Northern Highland malt from a single vintage, with fresh orchard fruit, toffee and subtle coastal notes.' },
  10:  { region: 'Blended Scotch',          price: '~£20',  desc: 'Accessible blended Scotch with a smooth, approachable finish of vanilla and soft oak.' },
  11:  { region: 'Scotch Single Malt',      price: '~£155', desc: 'A Speyside icon aged 21 years in port pipes, delivering lush dried fruit, chocolate and warming spice.' },
  12:  { region: 'Bourbon',                 price: '~£45',  desc: 'Light and spicy Kentucky bourbon with notes of citrus peel, honey, pepper and gentle oak.' },
  13:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Heavily peated Speyside malt with sweet toffee, earthy peat smoke and a long, warming finish.' },
  14:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Certified organic Speyside malt with fresh fruit, floral notes and a creamy, malty sweetness.' },
  15:  { region: 'Kentucky Wheat Whiskey',  price: '~£35',  desc: 'Rare American wheat whiskey from Heaven Hill; light, sweet and brimming with corn bread and honey.' },
  16:  { region: 'Scotch Single Malt',      price: '~£45',  desc: 'Richly sherried Islay malt aged 15 years; complex honey, dried fruit, vanilla and subtle peat smoke.' },
  17:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Unpeated Islay malt with a distinctive fruity, American oak character — lighter than most island drams.' },
  18:  { region: 'Bourbon',                 price: '~£30',  desc: 'Classic Kentucky bourbon from the Sazerac Company; caramel, vanilla, cherry and a hint of anise.' },
  19:  { region: 'Scotch Single Malt',      price: '~£80',  desc: 'Richly sherried Islay malt aged 18 years with dark fruit, chocolate, spice and a subtle maritime finish.' },
  20:  { region: 'Irish Whiskey',           price: '~£60',  desc: 'Triple-distilled Irish whiskey aged 16 years, with notes of toasted wood, dried fruit and rich honey.' },
  21:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Gentle Islay malt aged 12 years; lighter and more floral than most Islays, with honey and heather.' },
  22:  { region: 'Japanese Whisky',         price: '~£40',  desc: 'Light and delicate single grain whisky from Suntory\'s Chita distillery; citrus, honey and vanilla.' },
  23:  { region: 'Blended Scotch',          price: '~£195', desc: 'Ultra-premium 25-year-old blend of rare single malts and grain whiskies; dried fruit, spice and long finish.' },
  24:  { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Waxy Highland malt aged 14 years with a characteristic coastal richness, beeswax, peach and subtle spice.' },
  25:  { region: 'English Single Malt',     price: '~£45',  desc: 'Award-winning English single malt from the Cotswolds Distillery, with stone fruit, honey and vanilla.' },
  26:  { region: 'Blended Canadian',        price: '~£30',  desc: 'Canada\'s best-selling whisky; smooth and approachable with caramel, vanilla and a hint of rye spice.' },
  27:  { region: 'Scotch Single Malt',      price: '~£45',  desc: 'Sherried Highland malt finished in port pipes, delivering rich plum, dark chocolate and warming spice.' },
  28:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Elegant Highland malt aged 15 years; honeyed, gentle and lightly smoky with a warming finish.' },
  29:  { region: 'Scotch Single Malt',      price: '~£30',  desc: 'Accessible Highland single malt aged 12 years; light, grassy and gently spiced with a clean finish.' },
  30:  { region: 'Blended Scotch',          price: '~£130', desc: 'Prestigious 25-year-old blend from Dewar\'s; vanilla, honey, dried fruit and a smooth, long finish.' },
  31:  { region: 'Bourbon',                 price: '~£40',  desc: 'Flagship expression from Buffalo Trace; low-rye mash bill with oak, caramel and dried cherry.' },
  32:  { region: 'Bourbon',                 price: '~£35',  desc: 'Award-winning small batch bourbon with rich caramel, vanilla and a peppery, warming oak finish.' },
  33:  { region: 'English Single Malt',     price: '~£40',  desc: 'Pioneer English single malt from the English Whisky Company; sweet malt, vanilla and light toffee.' },
  34:  { region: 'Canadian Single Malt',    price: '~£55',  desc: 'Cape Breton\'s finest Canadian single malt; light, floral and gently peated with a cereal sweetness.' },
  35:  { region: 'Scotch Single Malt',      price: '~£60',  desc: 'Speyside malt aged 18 years in sherry casks; apricot, toffee, toasted almonds and warm spice.' },
  36:  { region: 'Scotch Single Malt',      price: '~£18',  desc: 'Affordable Speyside single malt from Aldi; light floral and fruity character with pleasant sweetness.' },
  37:  { region: 'Scotch Single Malt',      price: '~£30',  desc: 'Speyside malt with an unusual combination of wine cask finishing and smoky character — very versatile.' },
  38:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Campbeltown malt aged 15 years; lightly peated with dried fruit, vanilla and a maritime saltiness.' },
  39:  { region: 'Scotch Single Malt',      price: '~£45',  desc: 'Rich and full-flavoured Speyside whisky at natural cask strength; dried fruit, sherry and bold spice.' },
  40:  { region: 'Scotch Single Malt',      price: '~£180', desc: 'Rare Speyside aged in ice wine casks in a Canadian winter; tropical fruit, honey and a creamy richness.' },
  41:  { region: 'Scotch Single Malt',      price: '~£38',  desc: 'Highland malt from a revived distillery; light, grassy and floral with hints of peach and vanilla.' },
  42:  { region: 'Scotch Single Malt',      price: '~£90',  desc: 'Non-chill-filtered Lowland malt aged 21 years in sherry casks; rich fruitcake, chocolate and oak.' },
  43:  { region: 'Scotch Single Malt',      price: '~£55',  desc: 'Cask-strength Speyside bottled without chill-filtration; honeyed cereal, vanilla and a gentle nuttiness.' },
  44:  { region: 'Scotch Single Malt',      price: '~£45',  desc: 'Speyside malt finished in Quinta Ruban port casks; dark chocolate, orange peel and juicy red fruit.' },
  45:  { region: 'Scotch Single Malt',      price: '~£75',  desc: 'Richly sherried Speyside malt aged 18 years with dark fruit, Christmas spice and a warming finish.' },
  46:  { region: 'Canadian Whisky',         price: '~£50',  desc: 'Award-winning 4-grain Canadian whisky blending corn, malted barley, wheat and rye for complexity.' },
  47:  { region: 'Blended Scotch',          price: '~£30',  desc: 'Approachable blended Scotch from John & George Grant; vanilla, honey and a light, friendly character.' },
  48:  { region: 'Irish Whiskey',           price: '~£40',  desc: 'Traditional single pot still Irish whiskey matured in ex-bourbon and ex-sherry casks; fruity and spiced.' },
  49:  { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Old Orkney whisky from Highland Park, aged 18 years; heather, honey, dark fruit and balanced smoke.' },
  50:  { region: 'Blended Scotch',          price: '~£55',  desc: 'Triple distilled Canadian-owned Scotch blended malt; light and approachable with vanilla and gentle oak.' },
  51:  { region: 'Rye Whiskey',             price: '~£45',  desc: 'American craft rye from Hudson Whiskey; spicy and bold with pepper, dried fruit and light caramel.' },
  52:  { region: 'Canadian Whisky',         price: '~£45',  desc: 'Aged 18 years in new American oak, this blended Canadian delivers vanilla, caramel and toffee warmth.' },
  53:  { region: 'Irish Whiskey',           price: '~£60',  desc: 'Rare Jameson Reserve aged 18 years; rich, complex layers of sherry, dried fruit and toasted wood.' },
  54:  { region: 'Bourbon',                 price: '~£35',  desc: 'Small batch Kentucky bourbon with an approachable sweetness of vanilla, caramel and light oak spice.' },
  55:  { region: 'Blended Scotch',          price: '~£30',  desc: 'The world\'s best-selling Scotch; iconic smoky and sweet profile with malt, caramel and hints of fruit.' },
  56:  { region: 'Scotch Single Malt',      price: '~£60',  desc: 'Island malt aged 18 years with notes of tropical fruit, dried fig, warm spice and a maritime character.' },
  57:  { region: 'Taiwan Single Malt',      price: '~£65',  desc: 'Taiwanese malt finished in port casks; luscious red berries, dark chocolate and a lingering sweetness.' },
  58:  { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Islay malt with a unique salty, peaty and fruity combination; robust and complex with a long finish.' },
  59:  { region: 'Scotch Single Malt',      price: '~£38',  desc: 'Fife coastal single malt with a light, fresh character of vanilla, heather honey and gentle fruit.' },
  60:  { region: 'Bourbon',                 price: '~£35',  desc: 'Classic Kentucky straight bourbon aged 9 years; rich caramel, dried fruit and bold oak spice.' },
  61:  { region: 'Blended Scotch',          price: '~£20',  desc: 'Budget-friendly blended Scotch with a light, clean finish; popular mixer and easy sipping whisky.' },
  62:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Younger expression of Lagavulin distilled at 8 years; lighter in style but still intensely peaty.' },
  63:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Islay malt double-matured in quarter casks; full of caramel, vanilla, peat smoke and a briny finish.' },
  64:  { region: 'Scotch Single Malt',      price: '~£28',  desc: 'Highland malt aged 12 years; light and approachable with soft fruits, malt and a hint of smoke.' },
  65:  { region: 'Rye Whiskey',             price: '~£40',  desc: 'Unusual English rye whisky distilled in London; spicy, floral and complex with a distinctive character.' },
  66:  { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Campbeltown single malt aged without chill filtration; briny, oily, dried fruit and a spiced richness.' },
  67:  { region: 'USA Heavily Peated Malt', price: '~£55',  desc: 'American peated malt spirit bottled at high strength — an experimental and intensely smoky expression.' },
  68:  { region: 'Rye Whiskey',             price: '~£40',  desc: 'Canadian 100% rye whisky aged for four years; spicy, fruity and admirably complex for its price.' },
  69:  { region: 'Swedish Single Malt',     price: '~£55',  desc: 'Swedish single malt aged in Swedish oak; lightly floral, with white pepper, vanilla and fresh wood.' },
  70:  { region: 'Bourbon',                 price: '~£30',  desc: 'Hand-crafted Kentucky bourbon with soft red fruit, caramel and a straightforward, approachable finish.' },
  71:  { region: 'Blended Japanese',        price: '~£65',  desc: 'Japanese blended malt from Mars Shinshu; light citrus, coconut and a delicate, refreshing sweetness.' },
  72:  { region: 'Corn Whiskey',            price: '~£25',  desc: 'Classic American straight corn whisky; straightforward with sweet corn, light vanilla and a clean finish.' },
  73:  { region: 'Irish Whiskey',           price: '~£45',  desc: 'Triple-distilled Irish pot still whiskey; smooth with spiced green apple, vanilla and gentle oak.' },
  74:  { region: 'Bourbon',                 price: '~£45',  desc: 'Pot still small batch bourbon from Michter\'s; rich caramel, roasted nuts and warming spice.' },
  75:  { region: 'Rye Whiskey',             price: '~£50',  desc: 'Dutch 100% rye whisky aged in virgin oak; intense spice, coffee and dark chocolate character.' },
  76:  { region: 'Blended Scotch',          price: '~£25',  desc: 'Classic blended Scotch with a smooth, malty profile; light fruit, vanilla and easy-drinking character.' },
  77:  { region: 'Scotch Single Malt',      price: '~£55',  desc: 'Dufftown Speyside malt aged 12 years in sherry butts; deeply rich with dried plum, spice and oak.' },
  78:  { region: 'Blended Japanese',        price: '~£55',  desc: 'Japanese blend from Nikka; bold, full-flavoured with rich fruit, malt and a distinctively smoky note.' },
  79:  { region: 'Scotch Single Malt',      price: '~£55',  desc: 'West Highland coastal malt aged 14 years; sea salt, rich fruit, gentle smoke and warming spice.' },
  80:  { region: 'Bourbon',                 price: '~£30',  desc: 'Light, easy-drinking Kentucky bourbon; sweet vanilla, cherry and a mild, pleasant spice finish.' },
  81:  { region: 'Scotch Single Malt',      price: '~£65',  desc: 'Highland malt aged 18 years in ex-bourbon casks; rich vanilla, toffee and a warming finish.' },
  82:  { region: 'Indian Single Malt',      price: '~£45',  desc: 'Unpeated Indian single malt with a light, delicate character of coconut, vanilla and fresh orchard fruit.' },
  83:  { region: 'Welsh Single Malt',       price: '~£40',  desc: 'Welsh single malt finished in Madeira wine casks; rich and fruity with dark chocolate and dried fruit.' },
  84:  { region: 'Canadian Whisky',         price: '~£35',  desc: 'Aged 10 years in ex-bourbon barrels, this Canadian has notes of honey, vanilla and dried orchard fruit.' },
  85:  { region: 'Scotch Single Malt',      price: '~£35',  desc: 'Islay malt aged 8 years in first-fill bourbon casks; citrus peel, green apple and a fresh peatiness.' },
  86:  { region: 'Irish Whiskey',           price: '~£40',  desc: 'Single pot still Irish whiskey matured in ex-bourbon and Oloroso sherry casks; spiced and fruity.' },
  87:  { region: 'Blended Scotch',          price: '~£35',  desc: 'Peated blended malt with an earthy and maritime character; richer than many blended Scotch expressions.' },
  88:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Orcadian malt with a light and fresh profile; heather, honey and a mild smokiness from peat.' },
  89:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Heavily peated Islay malt from Smokehead; full of barbecue smoke, vanilla and a briny saltiness.' },
  90:  { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Campbeltown classic aged 10 years; brine, peat, lemon zest and a long, creamy, warming finish.' },
  91:  { region: 'Blended Australian',      price: '~£40',  desc: 'Innovative Australian whisky blending New World grain and malt; fruit-forward with soft sweetness.' },
  92:  { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Iconic Highland malt aged 10 years; classic notes of smoked pepper, brine, citrus and stone fruit.' },
  93:  { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Speyside malt bottled at cask strength from the acclaimed Tamdhu distillery; sherry-rich and robust.' },
  94:  { region: 'Irish Single Malt',       price: '~£40',  desc: 'Dublin-distilled Irish single malt aged in ex-rum, ex-bourbon and ex-sherry casks; complex and fruity.' },
  95:  { region: 'Finnish Single Malt',     price: '~£45',  desc: 'Finnish single malt aged 10 years; light vanilla, honey and a clean, refreshing Scandinavian character.' },
  96:  { region: 'Scotch Single Malt',      price: '~£35',  desc: 'Tobermory island malt aged 12 years; light and nutty with citrus, gentle spice and a maritime note.' },
  97:  { region: 'Blended Japanese',        price: '~£35',  desc: 'Suntory\'s signature Japanese blend for Highballs; light, floral and refreshing with citrus notes.' },
  98:  { region: 'Irish Whiskey',           price: '~£25',  desc: 'Classic triple-distilled Irish blend; smooth, light and approachable with vanilla and mild spice.' },
  99:  { region: 'American Single Malt',    price: '~£55',  desc: 'Seattle-distilled American single malt aged in new American oak; rich with caramel and dried fruit.' },
  100: { region: 'Rye Whiskey',             price: '~£70',  desc: 'Vermont-distilled 10-year-old rye with layers of spice, honey and a long, satisfying finish.' },
  101: { region: 'Bourbon',                 price: '~£35',  desc: 'Classic Woodford Reserve standard expression; rich with dried fruit, vanilla and bold rye spice.' },
  102: { region: 'Rye Whiskey',              price: '~£65',  desc: 'Highland rye malt distilled by Arbikie; unique Scottish rye character with floral and spiced notes.' },
  103: { region: 'Scotch Single Malt',      price: '~£30',  desc: 'Island malt aged 10 years from the Isle of Arran; fresh orchard fruit, vanilla and a honeyed sweetness.' },
  104: { region: 'Scotch Single Malt',      price: '~£38',  desc: 'Northern Highland malt aged 12 years; fresh and fruity with citrus peel, vanilla and light toffee.' },
  105: { region: 'Irish Single Malt',       price: '~£45',  desc: 'Single estate Irish single malt distilled in Kilkenny; fruity, light and richly malty in character.' },
  106: { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Speyside malt aged 12 years; rich and complex with citrus fruit, vanilla cream and Christmas spice.' },
  107: { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Speyside malt aged 15 years with triple-distilled Benromach character; honey, toffee and subtle smoke.' },
  108: { region: 'Scotch Single Malt',      price: '~£80',  desc: 'London craft distillery\'s Oloroso sherry cask expression; dark chocolate, dried fruit and rich spice.' },
  109: { region: 'Scotch Single Malt',      price: '~£35',  desc: 'Lowland malt aged in American oak; unusually light and approachable with gentle vanilla and fruit.' },
  110: { region: 'Blended Scotch',          price: '~£25',  desc: 'Budget-friendly bottled at low-strength; clean and sweet for easy sipping and mixing.' },
  111: { region: 'Irish Whiskey',           price: '~£60',  desc: 'Rare 7-year-old single pot still Irish whiskey from Mitchell & Son; fruity, spiced and vibrant.' },
  112: { region: 'Blended Scotch',          price: '~£35',  desc: 'Blended malt from Compass Box; fresh, vibrant and complex with citrus zest and floral notes.' },
  113: { region: 'Blended Scotch',          price: '~£25',  desc: 'Light and approachable 12-year-old blended Scotch; vanilla, cereal sweetness and a clean finish.' },
  114: { region: 'Scotch Single Malt',      price: '~£30',  desc: 'Accessible Highland single malt aged 12 years from Deanston; nutty, malty and lightly honeyed.' },
  115: { region: 'Scotch Single Malt',      price: '~£30',  desc: 'Macduff Speyside malt aged 12 years; light and floral with hints of apple blossom and vanilla.' },
  116: { region: 'Blended Scotch',          price: '~£65',  desc: 'Innovative four-times-aged blend from Dewar\'s matured in bourbon, oloroso, palo cortado and port.' },
  117: { region: 'Blended Scotch',          price: '~£35',  desc: 'Japanese-inspired blend using Mizunara oak finishing; honey, citrus and a delicate exotic spice.' },
  118: { region: 'Rye Whiskey',             price: '~£30',  desc: 'Kentucky straight rye from Heaven Hill; bold rye spice, cereal sweetness and warming pepper.' },
  119: { region: 'Scotch Single Malt',      price: '~£35',  desc: 'Northern Highland malt aged 12 years; fresh coastal notes, orchard fruit and a honeyed sweetness.' },
  120: { region: 'Blended Scotch',          price: '~£30',  desc: 'Speyside-style blended malt bottled at cask strength; fruity, rich and easy to enjoy.' },
  121: { region: 'Scotch Single Malt',      price: '~£30',  desc: 'Highland malt aged 12 years; lightly peated with fresh fruit and a gentle malty sweetness.' },
  122: { region: 'Scotch Single Malt',      price: '~£55',  desc: 'Campbeltown malt inspired by Victorian-era recipes; heavily peated and richly sherried with depth.' },
  123: { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Speyside malt aged 12 years; honey, vanilla and a hint of spice from first-fill American oak.' },
  124: { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Highland coastal malt aged 15 years; tropical fruit, vanilla and a warming, sea-breeze character.' },
  125: { region: 'Scotch Single Malt',      price: '~£45',  desc: 'Sherried Highland malt with a natural, rich complexity of dried fruit, malt and warming spice.' },
  126: { region: 'Scotch Single Malt',      price: '~£140', desc: 'Rich and complex Speyside aged 25 years in Oloroso sherry casks; fruit cake, spice and dark toffee.' },
  127: { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Glenfiddich\'s flagship 15-year-old; using a Solera vat blending process for layers of honey and spice.' },
  128: { region: 'Scotch Single Malt',      price: '~£35',  desc: 'Highland malt aged 12 years from the revived Glenglassaugh distillery; honey, malt and soft fruit.' },
  129: { region: 'Scotch Single Malt',      price: '~£30',  desc: 'Highland malt aged 10 years; smooth and light with summer berries, vanilla and a gentle sweetness.' },
  130: { region: 'Scotch Single Malt',      price: '~£35',  desc: 'Classic Lowland malt aged 12 years; light, gentle and floral with vanilla, lemon and cereal notes.' },
  131: { region: 'Bourbon',                 price: '~£50',  desc: 'Small-batch bourbon from Hudson Whiskey; rich caramel, dried cherry and light vanilla in a bold style.' },
  132: { region: 'Rye Whiskey',             price: '~£50',  desc: 'Fife distillery\'s rye-forward whisky; spicy and complex with fresh grain, black pepper and oak.' },
  133: { region: 'Blended Scotch',          price: '~£35',  desc: 'Blended malt range from J.G. Thomson; classic Scotch character with fruit, malt and gentle spice.' },
  134: { region: 'Irish Whiskey',           price: '~£60',  desc: 'Jameson 18-year-old limited release; smooth, nuanced and richly complex with dried fruit and wood.' },
  135: { region: 'Taiwan Single Malt',      price: '~£50',  desc: 'Entry-level Kavalan malt distilled in Yilan County; tropical fruit, vanilla and a creamy sweetness.' },
  136: { region: 'Rye Whiskey',             price: '~£55',  desc: 'Finnish organic malt rye whisky from Kyrö; herbal, spicy and refreshing with a characteristic rye bite.' },
  137: { region: 'Scotch Single Malt',      price: '~£45',  desc: 'First legal Fife malt in centuries; light, fresh and cereal-forward with subtle fruit and vanilla notes.' },
  138: { region: 'Single Grain Scotch',     price: '~£30',  desc: 'Loch Lomond peated single grain; unusual expression with smoke, citrus and a sweet cereal character.' },
  139: { region: 'Scotch Single Malt',      price: '~£50',  desc: 'Canadian-inspired Scottish single malt aged in Canadian virgin oak; rich and fruit-forward.' },
  140: { region: 'Blended Scotch',          price: '~£35',  desc: 'Islay-style blended malt from MacNair\'s; earthy, peated and maritime with a full, satisfying body.' },
  141: { region: 'English Single Malt',     price: '~£45',  desc: 'English single malt distilled in a traditional column still; lightly fruity with a distinctive grain richness.' },
  142: { region: 'Israel Single Malt',      price: '~£45',  desc: 'Israeli whisky from the M&H Distillery in Tel Aviv; tropical fruit, honey and a refreshing character.' },
  143: { region: 'Bourbon',                 price: '~£40',  desc: 'Small-batch Kentucky straight bourbon with toasted oak, dark cherry and warming spice.' },
  144: { region: 'Indian Single Malt',      price: '~£55',  desc: 'Aged in ex-Asava wine casks in the Himalayan foothills; exotic fruit, oak and warming Indian spice.' },
  145: { region: 'Australian Single Malt',  price: '~£45',  desc: 'Flagship Starward expression aged in Australian red wine barrels; fruity, vanilla-rich and approachable.' },
  146: { region: 'Irish Whiskey',           price: '~£35',  desc: 'Dublin\'s Teeling Small Batch aged in rum casks; honey, vanilla and a lively spiced sweetness.' },
  147: { region: 'Finnish Single Malt',     price: '~£55',  desc: 'Finnish peated single malt from Teerenpeli Distillery; earthy smoke balanced with sweet malt.' },
  148: { region: 'Scotch Single Malt',      price: '~£40',  desc: 'Skye malt from the revived Torabhaig distillery; peated, fruity and full of coastal character.' },
  149: { region: 'Irish Single Malt',       price: '~£60',  desc: 'Irish single malt aged in Bordeaux wine casks at Waterford Distillery using biodynamic barley.' },
  150: { region: 'Irish Whiskey',           price: '~£35',  desc: 'West Cork blended Irish whiskey finished in charred bog oak casks for a unique, smoky character.' },
  151: { region: 'Bourbon',                 price: '~£30',  desc: 'Iconic Kentucky bourbon bottled at 101 proof; bold, full-flavoured with vanilla, spice and long finish.' },
  152: { region: 'English Single Malt',     price: '~£45',  desc: 'Single malt from The Wire Works in Sheffield; fruity and floral with an innovative English character.' },
  153: { region: 'Irish Whiskey',           price: '~£35',  desc: 'Single pot still Irish whiskey with a distinctive copper pot character; fruity, spiced and smooth.' }
};

// ── Storage keys ─────────────────────────────────────────────────────────────
const ENTRIES_KEY  = 'whisky-club-entries';
const USED_KEY     = 'whisky-club-used';
const REVIEWS_KEY  = 'whisky-club-reviews';
const PRICES_KEY   = 'whisky-club-prices';
const SESSION_KEY  = 'whisky-club-session';

// ── JSONBin cloud sync ────────────────────────────────────────────────────────
const JSONBIN_BASE = 'https://api.jsonbin.io/v3';
const JSONBIN_KEY  = '$2a$10$7sndeshKqvuoqFr.LDI8eOHtIomBtO83.wPskt3Y33i0NfNekDisC';
const JSONBIN_BIN  = '69b6b0bbb7ec241ddc6e2ca0';

// ── Club members ──────────────────────────────────────────────────────────────
const PERSONS = ['Kev', 'John', 'Dan', 'Morgan'];

// ── App state ─────────────────────────────────────────────────────────────────
let entries  = JSON.parse(localStorage.getItem(ENTRIES_KEY)  || '{}');
let usedNums = JSON.parse(localStorage.getItem(USED_KEY)     || '[]');
let reviews  = JSON.parse(localStorage.getItem(REVIEWS_KEY)  || '[]');
let prices   = JSON.parse(localStorage.getItem(PRICES_KEY)   || '[]');

let currentNum     = null; // set to the active slot's number when reviewing
let currentNum1    = null; // slot 1 selected number
let currentNum2    = null; // slot 2 selected number
let activeSlot     = null; // which slot's review form is open (1 or 2)
let currentRatings = {};
let rollsLocked    = false; // roll buttons unlocked by default
