// ── Hardcoded whisky list (1–153) ─────────────────────────────────────────────
const WHISKY_LIST = [
  'Aberfeldy 21 Years in Age',
  "Aberlour A'bunadh",
  'Aerstone Sea Cask / Land Cask',
  'Amrut Fusion',
  'anCnoc 18 Years Old',
  'Ardbeg 10 Years Old',
  'The Ardmore Aged 20 Years',
  'Auchentoshan American Oak',
  'Balblair Vintage 2005',
  "Ballantine's Barrel Smooth",
  'The Balvenie PortWood Aged 21 Years',
  "Basil Hayden's",
  'The BenRiach Curiositas, Peated Malt',
  'Benromach Organic',
  'Bernheim Original Aged 7 Years',
  'Bowmore Aged 15 Years',
  'Bruichladdich The Classic Laddie',
  'Buffalo Trace',
  'Bunnahabhain 18 Year Old',
  'Bushmills Aged 16 Years',
  'Caol Ila Aged 12 Years',
  'The Chita',
  'Chivas Regal 25',
  'Clynelish Aged 14 Years',
  'Cotswolds',
  'Crown Royal Deluxe',
  'The Dalmore Port Wood Reserve',
  'Dalwhinnie 15 Years Old',
  'Deanston Aged 12 Years',
  "Dewar's Aged 25 Years, The Signature",
  'Eagle Rare',
  'Elijah Craig Small Batch',
  'The English Original',
  'Glen Breton Rare',
  'Glen Grant Aged 18 Years',
  'Glen Marnoch Speyside',
  'Glen Moray Fired Oak',
  'Glen Scotia Aged 15 Years',
  'Glenfarclas 105',
  'Glenfiddich Winter Storm',
  'Glenglassaugh Revival',
  'Glengoyne 21 Years',
  'The Glenlivet Nadurra',
  'Glenmorangie The Quinta Ruban',
  'Glenrothes 18 Years Old',
  'Gooderham & Worts Four Grain',
  "Great King Street Artist's Blend",
  'Green Spot',
  'Highland Park 18 Year Old Viking Pride',
  'House of Hazelwood Aged 18 Years',
  'Hudson Manhattan Rye',
  "J. P. Wiser's 18 Years Old",
  'Jameson Limited Reserve, 18 Years Old',
  "Jefferson's Very Small Batch",
  'Johnnie Walker Black Label',
  'Jura Aged 18 Years',
  'Kavalan Concertmaster',
  'Kilchoman Sanaig',
  'Kingsbarns Dream to Dram',
  'Knob Creek Kentucky Straight',
  'Label 5 Classic Black',
  'Lagavulin Aged 8 Years',
  'Laphroaig Quarter Cask',
  'Loch Lomond Aged 12 Years',
  'London Rye',
  'Longrow Peated',
  'Lost Spirits Abomination',
  'Lot No. 40',
  'Mackmyra Svensk EK',
  "Maker's Mark",
  'Mars Maltage Cosmo',
  'Mellow Corn',
  'Method and Madness Single Grain',
  "Michter's US+1 Kentucky Straight Bourbon",
  'Millstone 100 Rye',
  'Monkey Shoulder',
  'Mortlach Aged 12 Years',
  'Nikka From the Barrel',
  'Oban 14 Years Old',
  'Old Forester 86 Proof',
  'Old Pulteney Aged 18 Years',
  'Paul John Brilliance',
  'Penderyn Madeira Finish',
  'Pike Creek 10 Year Old',
  'Port Askaig Aged 8 Years',
  'Redbreast Aged 12 Years',
  'Rock Island',
  'Scapa Skiren',
  'Smokehead High Voltage',
  'Springbank Aged 10 Years',
  'Starward',
  'Talisker Aged 10 Years',
  'Tamdhu Batch Strength',
  'Teeling Single Malt',
  'Teerenpeli Aged 10 Years',
  'Tobermory Aged 12 Years',
  'Suntory Toki',
  'Tullamore D.E.W.',
  'Westland American Oak',
  'WhistlePig 10 Year Old',
  "Woodford Reserve Distiller's Select",
  'Arbikie 1794 Highland Rye',
  'Arran 10 Years Old',
  'Balblair 12 Year Old',
  'Ballykeefe Single Estate',
  'Benriach The Twelve',
  'Benromach Aged 15 Years',
  'Bimber Oloroso Cask',
  'Bladnoch Vinaya',
  'Blaze Scotch Whisky',
  'Blue Spot Aged 7 Years',
  'Compass Box Artist Blend',
  'Cutty Sark Aged 12 Years',
  'Deanstone 12 Years Old',
  'The Deveron Aged 12 Years',
  "Dewar's Double Double",
  "Dewar's Japanese Smooth",
  'Ezra Brooks',
  'Fettercairn Aged 12 Years',
  'The Gladstone Axe American Oak',
  'Glen Garioch Aged 12 Years',
  'Glen Scotia Victoriana',
  'The GlenAllachie Aged 12 Years',
  'Glencadam Aged 15 Years',
  'The GlenDronach Revival',
  'Glenfarclas Aged 25 Years',
  'Glenfiddich Solera 15',
  'Glenglassaugh 12 Years Old',
  'Glengoyne Aged 10 Years',
  'Glenkinchie 12 Year Old',
  'Hudson Whiskey NY Bright Lights, Big Bourbon',
  'InchDairnie RyeLaw',
  'J. G. Thomson Blended Malt Range',
  'Jameson 18 Years',
  'Kavalan Distillery Select No1',
  'Kyro Malt Rye',
  'Lindores MCDXCIV',
  'Loch Lomond Peated Single Grain',
  "Macaloney's Caledonian Glenloy",
  "MacNair's Lum Reek",
  'Masthouse Column Malt Whisky',
  'Milk & Honey Classic',
  'New Riff Kentucky Straight Bourbon',
  'Rampur Asava',
  'Starward Nova',
  'Teeling Small Batch',
  'Teerenpeli Kulo',
  'Torabhaig The Legacy Series',
  'Waterford Biodynamic Luna 1.1',
  'West Cork Bog Oak Charred Cask',
  'Wild Turkey 101 Kentucky Straight Bourbon',
  'Wire Works Single Malt English Whisky',
  'Writers Tears Copper Pot'
];

// ── Whisky info (category/type) ───────────────────────────────────────────────
const WHISKY_DATA = {
  1:   { region: 'Scotch Single Malt' },
  2:   { region: 'Scotch Single Malt' },
  3:   { region: 'Scotch Single Malt' },
  4:   { region: 'Scotch Single Malt' },
  5:   { region: 'Scotch Single Malt' },
  6:   { region: 'Scotch Single Malt' },
  7:   { region: 'Scotch Single Malt' },
  8:   { region: 'Scotch Single Malt' },
  9:   { region: 'Scotch Single Malt' },
  10:  { region: 'Blended Scotch' },
  11:  { region: 'Scotch Single Malt' },
  12:  { region: 'Bourbon' },
  13:  { region: 'Scotch Single Malt' },
  14:  { region: 'Scotch Single Malt' },
  15:  { region: 'Kentucky Wheat Whiskey' },
  16:  { region: 'Scotch Single Malt' },
  17:  { region: 'Scotch Single Malt' },
  18:  { region: 'Bourbon' },
  19:  { region: 'Scotch Single Malt' },
  20:  { region: 'Irish Whiskey' },
  21:  { region: 'Scotch Single Malt' },
  22:  { region: 'Japanese Whisky' },
  23:  { region: 'Blended Scotch' },
  24:  { region: 'Scotch Single Malt' },
  25:  { region: 'English Single Malt' },
  26:  { region: 'Blended Canadian' },
  27:  { region: 'Scotch Single Malt' },
  28:  { region: 'Scotch Single Malt' },
  29:  { region: 'Scotch Single Malt' },
  30:  { region: 'Blended Scotch' },
  31:  { region: 'Bourbon' },
  32:  { region: 'Bourbon' },
  33:  { region: 'English Single Malt' },
  34:  { region: 'Canadian Single Malt' },
  35:  { region: 'Scotch Single Malt' },
  36:  { region: 'Scotch Single Malt' },
  37:  { region: 'Scotch Single Malt' },
  38:  { region: 'Scotch Single Malt' },
  39:  { region: 'Scotch Single Malt' },
  40:  { region: 'Scotch Single Malt' },
  41:  { region: 'Scotch Single Malt' },
  42:  { region: 'Scotch Single Malt' },
  43:  { region: 'Scotch Single Malt' },
  44:  { region: 'Scotch Single Malt' },
  45:  { region: 'Scotch Single Malt' },
  46:  { region: 'Canadian Whisky' },
  47:  { region: 'Blended Scotch' },
  48:  { region: 'Irish Whiskey' },
  49:  { region: 'Scotch Single Malt' },
  50:  { region: 'Blended Scotch' },
  51:  { region: 'Rye Whiskey' },
  52:  { region: 'Canadian Whisky' },
  53:  { region: 'Irish Whiskey' },
  54:  { region: 'Bourbon' },
  55:  { region: 'Blended Scotch' },
  56:  { region: 'Scotch Single Malt' },
  57:  { region: 'Taiwan Single Malt' },
  58:  { region: 'Scotch Single Malt' },
  59:  { region: 'Scotch Single Malt' },
  60:  { region: 'Bourbon' },
  61:  { region: 'Blended Scotch' },
  62:  { region: 'Scotch Single Malt' },
  63:  { region: 'Scotch Single Malt' },
  64:  { region: 'Scotch Single Malt' },
  65:  { region: 'Rye Whiskey' },
  66:  { region: 'Scotch Single Malt' },
  67:  { region: 'USA Heavily Peated Malt' },
  68:  { region: 'Rye Whiskey' },
  69:  { region: 'Swedish Single Malt' },
  70:  { region: 'Bourbon' },
  71:  { region: 'Blended Japanese' },
  72:  { region: 'Corn Whiskey' },
  73:  { region: 'Irish Whiskey' },
  74:  { region: 'Bourbon' },
  75:  { region: 'Rye Whiskey' },
  76:  { region: 'Blended Scotch' },
  77:  { region: 'Scotch Single Malt' },
  78:  { region: 'Blended Japanese' },
  79:  { region: 'Scotch Single Malt' },
  80:  { region: 'Bourbon' },
  81:  { region: 'Scotch Single Malt' },
  82:  { region: 'Indian Single Malt' },
  83:  { region: 'Welsh Single Malt' },
  84:  { region: 'Canadian Whisky' },
  85:  { region: 'Scotch Single Malt' },
  86:  { region: 'Irish Whiskey' },
  87:  { region: 'Blended Scotch' },
  88:  { region: 'Scotch Single Malt' },
  89:  { region: 'Scotch Single Malt' },
  90:  { region: 'Scotch Single Malt' },
  91:  { region: 'Blended Australian' },
  92:  { region: 'Scotch Single Malt' },
  93:  { region: 'Scotch Single Malt' },
  94:  { region: 'Irish Single Malt' },
  95:  { region: 'Finnish Single Malt' },
  96:  { region: 'Scotch Single Malt' },
  97:  { region: 'Blended Japanese' },
  98:  { region: 'Irish Whiskey' },
  99:  { region: 'American Single Malt' },
  100: { region: 'Rye Whiskey' },
  101: { region: 'Bourbon' },
  102: { region: 'Rye Whiskey' },
  103: { region: 'Scotch Single Malt' },
  104: { region: 'Scotch Single Malt' },
  105: { region: 'Irish Single Malt' },
  106: { region: 'Scotch Single Malt' },
  107: { region: 'Scotch Single Malt' },
  108: { region: 'English Single Malt' },
  109: { region: 'Scotch Single Malt' },
  110: { region: 'Blended Scotch' },
  111: { region: 'Irish Whiskey' },
  112: { region: 'Blended Scotch' },
  113: { region: 'Blended Scotch' },
  114: { region: 'Scotch Single Malt' },
  115: { region: 'Scotch Single Malt' },
  116: { region: 'Blended Scotch' },
  117: { region: 'Blended Scotch' },
  118: { region: 'Rye Whiskey' },
  119: { region: 'Scotch Single Malt' },
  120: { region: 'Blended Scotch' },
  121: { region: 'Scotch Single Malt' },
  122: { region: 'Scotch Single Malt' },
  123: { region: 'Scotch Single Malt' },
  124: { region: 'Scotch Single Malt' },
  125: { region: 'Scotch Single Malt' },
  126: { region: 'Scotch Single Malt' },
  127: { region: 'Scotch Single Malt' },
  128: { region: 'Scotch Single Malt' },
  129: { region: 'Scotch Single Malt' },
  130: { region: 'Scotch Single Malt' },
  131: { region: 'Bourbon' },
  132: { region: 'Rye Whiskey' },
  133: { region: 'Blended Scotch' },
  134: { region: 'Irish Whiskey' },
  135: { region: 'Taiwan Single Malt' },
  136: { region: 'Rye Whiskey' },
  137: { region: 'Scotch Single Malt' },
  138: { region: 'Single Grain Scotch' },
  139: { region: 'Scotch Single Malt' },
  140: { region: 'Blended Scotch' },
  141: { region: 'English Single Malt' },
  142: { region: 'Israel Single Malt' },
  143: { region: 'Bourbon' },
  144: { region: 'Indian Single Malt' },
  145: { region: 'American Single Malt' },
  146: { region: 'Irish Whiskey' },
  147: { region: 'Finnish Single Malt' },
  148: { region: 'Scotch Single Malt' },
  149: { region: 'Irish Single Malt' },
  150: { region: 'Irish Whiskey' },
  151: { region: 'Bourbon' },
  152: { region: 'English Single Malt' },
  153: { region: 'Irish Whiskey' }
};

// ── Storage keys ─────────────────────────────────────────────────────────────
const ENTRIES_KEY  = 'whisky-club-entries';
const USED_KEY     = 'whisky-club-used';
const REVIEWS_KEY  = 'whisky-club-reviews';
const PRICES_KEY   = 'whisky-club-prices';
const SESSION_KEY  = 'whisky-club-session';

// ── JSONBin cloud sync ────────────────────────────────────────────────────────
const JSONBIN_BASE = 'https://api.jsonbin.io/v3';
const JSONBIN_KEY  = '$2a$10$7sndeshKqvuoqFr.LDI8eOHtIomBtO83.wPskt3Y33i0NfNekDisC';
const JSONBIN_BIN  = '69b6b0bbb7ec241ddc6e2ca0';

// ── Club members ──────────────────────────────────────────────────────────────
const PERSONS = ['Kev', 'John', 'Dan', 'Morgan'];

// ── App state ─────────────────────────────────────────────────────────────────
let entries  = JSON.parse(localStorage.getItem(ENTRIES_KEY)  || '{}');
let usedNums = JSON.parse(localStorage.getItem(USED_KEY)     || '[]');
let reviews  = JSON.parse(localStorage.getItem(REVIEWS_KEY)  || '[]');
let prices   = JSON.parse(localStorage.getItem(PRICES_KEY)   || '[]');

let currentNum     = null; // set to the active slot's number when reviewing
let currentNum1    = null; // slot 1 selected number
let currentNum2    = null; // slot 2 selected number
let activeSlot     = null; // which slot's review form is open (1 or 2)
let currentRatings = {};
let rollsLocked    = false; // roll buttons unlocked by default
